name: aml
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.13
  - pip
  # --------- visualize & image processing -------- #
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - scikit-image
  # --------- machine learning --------- #
  - conda-forge::scikit-learn
  - conda-forge::imbalanced-learn
  - conda-forge::mlxtend
  # --------- juypter --------- #
  - conda-forge::jupyter
  - ipykernel
  - pip:
      - argcomplete>=3.5.3
      - black>=25.1.0
      - isort>=6.0.1
      - jinja2>=3.1.5
      - jupyter-black>=0.4.0
      - mypy>=1.15.0
      - optuna>=4.2.1
      - pre-commit>=4.1.0
      - pyrootutils>=1.0.4
      - python-dotenv>=1.0.1
      - rich>=13.9.4
      - ruff>=0.9.9
